googlefonts/axisregistry

CHANGELOG.md, Lib/axisregistry/__init__.py, tests/test_axisregistry_api.py
(issue #7)
Also updated the CHANGELOG.md file.
=> add code test to avoid spaces in fallback names

Lib/axisregistry/__init__.py
Fixes: https://github.com/googlefonts/gftools/issues/576
=> AxisRegistry: add items method

Lib/axisregistry/data/element_grid.textproto
PR to follow up on the inclusion of the new custom axis `EGRD` https://github.com/googlefonts/axisregistry/issues/16
=> Add EGRD custom axis

Lib/axisregistry/data/edge_highlight.textproto, Lib/axisregistry/data/extrusion_depth.textproto
Ref #58 and #60. Don't close those until axis images and description review is completed.
cc @justvanrossum
=> Add Nabla axes for Extrusion Depth and Edge Highlight

tests/test_axisregistry_api.py
=> All axes must have a fallback

Lib/axisregistry/__init__.py, tests/test_axisregistry_api.py, tox.ini
Reverts googlefonts/axisregistry#70
=> Revert "sync with google/fonts"

Lib/axisregistry/data/extrusion_depth.textproto
Based on discussion with Sarah Daily.
This achieves consistency with the EHLT axis description (also used in Nabla) and seems more easily understandable.
=> Update EDPT description

Lib/axisregistry/data/hyper_expansion.textproto
Closes #11 
For the fallbacks, I don't think it is necessarily what we shall do, but these are the current fallback for Readex Pro and Lexend (although not sure they will follow the exact same value).
=> HyperExpansion axis added

Lib/axisregistry/data/flair.textproto
=> Update flair.textproto to correct precision to -1

Lib/axisregistry/data/element_shape.textproto
PR to follow up on the inclusion of the new custom axis `ESHP` https://github.com/googlefonts/axisregistry/issues/15
=> Add ELSH custom axis

Lib/axisregistry/data/year.textproto
PR to follow up on the inclusion of the new custom axis YEAR #19
=> Add YEAR custom axis

Lib/axisregistry/data/x_rotation.textproto
PR to follow up on the inclusion of the new custom axis `XROT` #41
=> Add XROT custom axis

Lib/axisregistry/data/y_rotation.textproto
PR to follow up on the inclusion of the new custom axis `YROT` #41
=> Add YROT custom axis

CHANGELOG.md
=> update contents of CHANGELOG

.github/ISSUE_TEMPLATE/1_add-axis.md, .github/ISSUE_TEMPLATE/2_anything-else.md
This PR adds two Issues templates
=> Issue Templates 

.github/ISSUE_TEMPLATE/1_add-axis.md
Indicating also to declare the proposed Axis name in the Issue title
=> add-axis tempalte small fix

.github/ISSUE_TEMPLATE/1_add-axis.md
This PR includes:
- Requirements section pointing to the Axis Registry Protocol in the GF-Guide
- Wording editing fixes
[Rendered file](https://github.com/googlefonts/axisregistry/pull/114/files?short_path=aee619a#diff-aee619a6710dfa68e555e787259ef3021b847155fed8b2bd4d792ba6e9cde858)
=> Add Axis issue template updated

Lib/axisregistry/data/x_rotation.textproto, Lib/axisregistry/data/y_rotation.textproto
=> XROT, YROT description, Letters replaced by Glyphs

Lib/axisregistry/data/morph.textproto
This axis is introduced by Kablammo font, in replace of replace `MUTA`
=> Adding [MORF] Morph custom axis

Lib/axisregistry/data/z_rotation.textproto
PR to follow up on the inclusion of the new custom axis `ZROT Rotation in Z` #129
=> Adding [ZROT] Rotation in Z custom axis

Lib/axisregistry/__init__.py
=> If we delete a name STAT was using, put it back

Lib/axisregistry/data/x_element_alignment.textproto
=> Add Horizontal Element Alignment [XELA] axis

Lib/axisregistry/data/x_position_paint_1.textproto
This PR adds `Horizontal Position Paint 1` discussed in #113 and introduced by Bitcount fonts.
=> Add Horizontal Position Paint 1 [XPN1] axis

Lib/axisregistry/data/y_element_alignment.textproto
=> YELA desc updated to match reviewed XELA

Lib/axisregistry/data/slant.textproto
=> Slant axis description updated with range interpretation

.github/workflows/rust.yml, Cargo.toml, build.rs, src/lib.rs, src/monkeypatching.rs, src/nametable.rs, src/stat.rs
- **Initial commit**
- **Workable Rust crate, no stat yet**
- **Missing files for rust crate, finish off and test**
- **Implement aggressive/conservative renaming**
- **First cut at build_stat, no tests yet since they’re all TTX**
- **STAT table test and fixes**
- **No debugging print**
=> Add Rust port

.github/workflows/tox.yml, Lib/axisregistry/__init__.py, requirements.txt, setup.py, tests/data/OpenSans-Italic[wdth,wght]_STAT.ttx, tests/data/OpenSansCondensed-Italic[wght]_STAT.ttx, tests/data/OpenSansCondensed[wght]_STAT.ttx, tests/data/OpenSans[wdth,wght]_STAT.ttx
=> Fix axis duplication in build_stat
