Lib/axisregistry/data/casual.textproto
Lib/axisregistry/data/cursive.textproto
Lib/axisregistry/data/fill.textproto
Lib/axisregistry/data/grade.textproto
Lib/axisregistry/data/monospace.textproto
Lib/axisregistry/data/optical_size.textproto
Lib/axisregistry/data/softness.textproto
Lib/axisregistry/data/weight.textproto
Lib/axisregistry/data/width.textproto
Lib/axisregistry/data/wonky.textproto
Lib/axisregistry/data/x_opaque.textproto
Lib/axisregistry/data/x_transparent.textproto
Lib/axisregistry/data/y_opaque.textproto
Lib/axisregistry/data/y_transparent_ascender.textproto
Lib/axisregistry/data/y_transparent_descender.textproto
Lib/axisregistry/data/y_transparent_figures.textproto
Lib/axisregistry/data/y_transparent_lowercase.textproto
Lib/axisregistry/data/y_transparent_uppercase.textproto

With the upcoming "tooltips" that explain more about axes, and with the GFK glossary pages describing the axes in more detail, I've made them much shorter.
Parametric axes names are eliding "Parametric" here too.

Reduce the length of descriptions and rename parametric axes

---

Lib/axisregistry/data/weight.textproto
Lib/axisregistry/data/width.textproto
Lib/axisregistry/data/y_transparent_descender.textproto

Small copy fixes, for pushing after I/O

y_transparent_descender.textproto Use depth, not height

---

.github/workflows/tox.yml
Lib/axisregistry/__init__.py
setup.py
test_requirements.txt
tests/test_names.py
tox.ini

#49 ran without a hitch because I stupidly forgot to wire up the unit tests. This PR will fix the typo which passed in that pr and also enable tests for tox.

Fix typo and ensure tox runs tests correctly

---

Lib/axisregistry/data/edge_highlight.textproto
Lib/axisregistry/data/element_grid.textproto
Lib/axisregistry/data/extrusion_depth.textproto

We'll sync this repo with google/fonts axisregistry directory in two stages.  First step here is to bring in all downstream edits to textproto files that we want to preserve.  The second stage will be to git subtree pull this repo into google/fonts axisregistry directory and take all other changes from this side.  We should then be in sync and can use edits here only and git subtree pulls to import axisregistry edits into google/fonts
cc @rsheeter

Sync axis registration changes with google/fonts axisregistry directory

---

Lib/axisregistry/data/italic.textproto

Since we don't support the ital axis, in fact, and require separate roman and italic files at the moment (due to concerns eg in https://arrowtype.github.io/vf-slnt-test), then we should reflect that actual implementation in the axis definition. 
Since we have zero families with an ital axis, this should be a no-op when pushed; but this is a very peculiar move, and may have unexpected consequences when pushed.

italic.textproto reduce precision from -1 to 0

---

Lib/axisregistry/data/element_grid.textproto

Element shape is ELSH, so Element grid should be ELGR. This is also how it is stated in the spreadsheet.
cc @chrissimpkins @vv-monsalve @davelab6

Update element_grid.textproto EGRD -> ELGR

---

Lib/axisregistry/data/flair.textproto

Since the font requiring this axis hasn't been onboarded the previous fallbacks (normal and flair) could be removed.

FLAIR: Adjusting fallbacks to leave only the Default

---

Lib/axisregistry/__init__.py
tests/data/OpenSans-Italic[wdth,wght]_STAT.ttx
tests/data/OpenSansCondensed-Italic[wght]_STAT.ttx
tests/data/OpenSansCondensed[wght]_STAT.ttx
tests/data/OpenSans[wdth,wght]_STAT.ttx
tests/data/Wonky[wdth,wght]_STAT.ttx

When a user runs `build_stat`, it will remove any name records which are associated with the old stat table. However, Stat axis names and fvar axis name often use the name record. If a name record is also being used for an fvar axis name, we should skip it,
Fixes https://github.com/googlefonts/gftools/issues/619
cc @simoncozens

build_stat: do not rm fvar axis name records

---

Lib/axisregistry/__init__.py
tests/data/OpenSansCondensed-Italic[wght]_STAT.ttx
tests/data/OpenSansCondensed[wght]_STAT.ttx

In https://github.com/google/fonts/pull/5338, we're finding that build_stat is removing nameID 2 when it should be preserved. In fact, all nameIDs <= 25 are used in font application menus so they should all be preserved.
cc @simoncozens

fix_stat do not drop nameids <= 25

---

Lib/axisregistry/data/roundness.textproto

PR to follow up on the inclusion of the new custom axis ROND [#59](https://github.com/googlefonts/axisregistry/issues/59)

Adding ROND

---

Lib/axisregistry/__init__.py
tests/data/OpenSans-Italic[wdth,wght]_STAT.ttx
tests/data/OpenSansCondensed-Italic[wght]_STAT.ttx
tests/data/OpenSansCondensed[wght]_STAT.ttx
tests/data/OpenSans[wdth,wght]_STAT.ttx
tests/test_names.py

Currently, if we're generating a STAT table for a variable font family which contains Roman and Italic fonts, the Roman font's Italic axis will include an axisvalue whose name is "Normal" when we actually want "Roman". We're getting this due to me previously hardcoding the implementation. The new implementation will now get the default axisvalue for the given axis and then elide it.
Fixes https://github.com/google/fonts/pull/5591
cc @RosaWagner

build_stat: improve elided axisvalues

---

Lib/axisregistry/data/informality.textproto

PR to follow up on the inclusion of the new custom axis required for [Shantell Sans](https://next--shantell-sans.netlify.app/), it would replace originally proposed Irregularity https://github.com/googlefonts/axisregistry/issues/37
@thundernixon I'm opening this new PR since the textproto file name also needed to change.

Add Informality [INFM] axis

---

Lib/axisregistry/data/bounce.textproto

PR to follow up on the inclusion of the new custom axis Bounce, `BNCE`. https://github.com/googlefonts/axisregistry/issues/38
Required for the upcoming release of [Shantell Sans](https://next--shantell-sans.netlify.app).

Add Bounce [BNCE] axis

---

tests/data/RobotoFlex[GRAD,XOPQ,XTRA,YOPQ,YTAS,YTDE,YTFI,YTLC,YTUC,opsz,slnt,wdth,wght]_STAT.ttx

Make expected values consistent with changes introduced at https://github.com/googlefonts/axisregistry/pull/89

Update Roboto Flex optical size expected string casing in ttx

---

Lib/axisregistry/data/mutation.textproto

PR to follow up on the inclusion of the new custom axis Mutation `MUTA` #9 
Required for the upcoming font Kablammo.

Add Mutation [MUTA] axis 

---

Lib/axisregistry/__init__.py

When rebuilding the name table after replacing fvar instances, we make sure that we don't delete any name IDs which are used in the STAT table. However, currently we only look in the axis value list of the STAT table; we also need to read the design axis list as well.

Also protect STAT table name IDs from the axis list

---

Lib/axisregistry/__init__.py
tests/test_names.py

Update the fsSelection, mac style and usWeightClass when `build_name_table` is called.

build_name_table: set bits as well

---

Lib/axisregistry/data/sharpness.textproto

This axis is introduced by the Geologica font.
I changed the description, making it somewhat coordinated with how [ROND](https://github.com/googlefonts/axisregistry/blob/main/Lib/axisregistry/data/roundness.textproto) axis was described and clarifying the value ranges.
Ideally, this PR should be included in the same git pull subtree alongside the deletion of `MUTA` and the inclusion of `YALN`

Adding [SHRP] Sharpness custom Axis

---

Lib/axisregistry/data/y_alignment.textproto

PR to follow up on the inclusion of the new custom axis `YALN Y Alignment` #106 
Required for the Wavefont.

Adding [YALN] Y Alignment custom Axis 

---

tests/test_wellformed.py

Although the proto definition suggests that some fields are optional, actually most fields are required. We gather a list of *actually* optional fields, and check that everything in the registry has values present for the rest.

Add test for proto wellformedness (no missing required fields)

---

Lib/axisregistry/data/scanlines.textproto

PR to follow up on the inclusion of the new custom axis `[SCAN] Scanlines` https://github.com/googlefonts/axisregistry/issues/18
This axis is introduced by Homecomputer Sixtyfour and Workbench fonts.

Adding [SCAN] Scanlines custom Axis

---

Lib/axisregistry/data/bleed.textproto

PR to follow up on the inclusion of the new custom axis `[BLED] Bleed` #17 
This axis is introduced by Homecomputer Sixtyfour and Workbench fonts.

Adding [BLED] Bleed custom Axis

---

Lib/axisregistry/__init__.py

My previous PR caused a failure on STAT tables with no axis values; check the array before dereferencing it.

Don't fail if there are no axis values

---

Lib/axisregistry/__init__.py
tests/test_names.py

Allows for a family of related fonts to share same (untouched) name IDs, such as copyright. Test says it all:
```python
font = TTFont(mavenpro_fp)
build_name_table(font, "Raven Am", "Regular", aggressive=True)
_test_names(font, {
(0, 3, 1, 0x409): 'Copyright 2011 The Raven Am Project Authors (http://www.vissol.co.uk/mavenpro/), with Reserved Font Name "Raven Am".',
(4, 3, 1, 0x409): "Raven Am Regular"
})
font = TTFont(mavenpro_fp)
build_name_table(font, "Raven Am", "Regular", aggressive=False)
_test_names(font, {
(0, 3, 1, 0x409): 'Copyright 2011 The Maven Pro Project Authors (http://www.vissol.co.uk/mavenpro/), with Reserved Font Name "Maven Pro".',
(4, 3, 1, 0x409): "Raven Am Regular"
})
```

Allow less aggressive renames

---

Lib/axisregistry/data/element_expansion.textproto

This PR adds `Element Expansion` axis #128 introduced by Bitcound fonts

Add Element Expansion [ELXP] axis

---

Lib/axisregistry/data/size_paint_1.textproto

This PR adds `Size of Paint 1` #117 introduced by Bitcount fonts.

Add Size of Paint 1 [SZP1] axis

---

Lib/axisregistry/data/size_paint_2.textproto

This PR adds the second Size of Paint discussed in #117, introduced by Bitcount fonts.
@davelab6 I've reinstated the line `Paint 2 is in front of Paint 1.` for this axis description.
Related PR #167

Add Size of Paint 2 [SZP2] axis

---

Lib/axisregistry/data/x_position_paint_2.textproto

This PR adds the second Size of Paint discussed in https://github.com/googlefonts/axisregistry/issues/113, introduced by Bitcount fonts.
Related PR #169

Add Horizontal Position Paint 2 [XPN2] axis

---

Lib/axisregistry/data/y_position_paint_1.textproto

This PR adds `Vertical Position of Paint 1` discussed in https://github.com/googlefonts/axisregistry/issues/116 and introduced by Bitcount fonts.

Add Vertical Position of Paint 1 [YPN1] axis

---

Lib/axisregistry/data/y_position_paint_2.textproto

This PR adds the second Vertical Position axis discussed in https://github.com/googlefonts/axisregistry/issues/116, introduced by Bitcount fonts.
Related PR https://github.com/googlefonts/axisregistry/pull/171

Add Vertical Position of Paint 2 [YPN2] axis

---

Lib/axisregistry/data/x_element_alignment.textproto

The default value was always supposed to be `0`. This will unblock [Sixtyfour Convergence](https://github.com/google/fonts/pull/7919)

XELA default changed to 0

---

Lib/axisregistry/__init__.py

I've found these are needed in order to get a font to work in Windows MS Office. Viv has also pointed this out in the past so apologies for the delay.

build_fvar: add fvar instance ps names

---

Lib/axisregistry/data/y_vertical_extension.textproto

PR to follow up on the inclusion of the new custom axis `YEXT Vertical Extension` following the latest definitions agreed on https://github.com/googlefonts/axisregistry/issues/135#issuecomment-2052244984
The Playwrite project defined this Axis. But we should register it now since Emery Cubic https://github.com/google/fonts/issues/6124 needs it

Adding [YEXT] Vertical Extension axis

---

Lib/axisregistry/__init__.py

See googlefonts/gftools#469
As of the latest Font Bakery release, [the no_mac_entries check has been promoted to the Universal profile](https://github.com/fonttools/fontbakery/blob/main/CHANGELOG.md#0130a0-2024-sep-13), but by default, gftools and axisregistry insert Mac names when populating STAT and fvar.
googlefonts/gftools#1077 has been merged to prevent adding Mac names to STAT, and so this PR follows up to prevent Mac names from being added to fvar too. This is already the behaviour of the in-progress Rust port of axisregistry, and so only the original Python version has been adjusted.
This is the right approach for the particular project I am looking at, but I would like to confirm that this is the right fix - as opposed to, e.g., making the Mac names opt-out - to make sure that …

Do not add Mac names when populating the fvar table

---

Lib/axisregistry/__init__.py

This small PR resolves the annoying deprecation warnings of the `logger` library:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```

Resolve logger warnings
